---
output: github_document
---

```{r setup, include=FALSE}
# ---
# output:
#   html_document:
#     highlight: py
#     css: "style.css"
#     code_folding: show
#     toc: true
#     toc_depth: 2
#     toc_float:
#       collapsed: false
#       smooth_scroll: false
# ---
        
knitr::opts_chunk$set(echo = TRUE, 
                      eval = T,
                      class.source="rsource",
                      class.output="routput")
# library(clavaan)

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "vignettes",
  out.width = "100%"
)

options(tibble.print_min = 5, tibble.print_max = 5)
```

# clavaan 

## Overview

This package is censored SEM.

## Install

Install the latest release from CRAN:

```{r eval = F}
devtools::install_github("sooyongl/clavaan")
```

The documentation is available at [here](https://sooyongl.github.io/clavaan/).


```{r}
library(clavaan)
library(lavaan)
library(tidyverse)
```

## Generate Latent growth curve model data

```{r}
unc.data <- lavaan::simulateData('
                     I =~ 1*y1 + 1*y2 + 1*y3 + 1*y4 + 1*y5
                     S =~ 0*y1 + 1*y2 + 2*y3 + 3*y4 + 4*y5

                     I ~ 3*1
                     S ~ 0.5*1

                     I ~~ 1*I + 0.2*S
                     S ~~ 0.5*S
                     ', model.type = 'growth',
                     sample.nobs = 500)
```

## Censore data

```{r}
censored_prop <- c(left = 0.2, right = 0.8)

cen_points <- clavaan:::cenPoint(x = unc.data,
                       lower_quant = censored_prop[1],
                       upper_quant = censored_prop[2])


cen.data <- clavaan:::cenData(unc.data, cen_points) %>%
  data.frame() %>%
  set_names(names(unc.data))
```


## Compare {.tabset}

```{r}
model =
'I =~ 1*y1 + 1*y2 + 1*y3 + 1*y4 + 1*y5
 S =~ 0*y1 + 1*y2 + 2*y3 + 3*y4 + 4*y5

 I ~ 1
 S ~ 1

 I ~~ I + S
 S ~~ S'
```

### clavaan
<!-- <div class = "row"> -->
<!-- <div class = "col-md-6"> -->
```{r}
cgrowth(model, data = cen.data, bounds = cen_points) %>%
  summary()
```
<!-- </div> -->

### lavaan with censored data
<!-- <div class = "col-md-6"> -->
```{r}
growth(model,data = cen.data) %>%
  summary()
```
<!-- </div> -->
<!-- </div> -->

### lavaan with original data
```{r}
growth(model,data = unc.data) %>%
  summary()
```


```{r}
sessionInfo()
```

